apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: hello-ctc
  name: hello-ctc-blue-dc
  namespace: ctc-devel
spec:
  replicas: 1
  selector:
    app: hello-ctc
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      labels:
        app: hello-ctc
        version: blue
    spec:
      containers:
      - env:
        - name: SERVICE_VERSION
          value: Version8
        image: image-registry.openshift-image-registry.svc:5000/ctc-devel/hello-ctc-blue 
        imagePullPolicy: Always
        name: hello-ctc
        ports:
        - containerPort: 8080
          protocol: TCP

